# Generated by Django 6.0.1 on 2026-04-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Proxy', 'Proxy'), ('Directo', 'Directo')], max_length=50, null=True)),
                ('tipo_ip', models.CharField(blank=True, choices=[('Pública', 'Pública'), ('Privada', 'Privada')], max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat_vlan.vlan')),
            ],
        ),
    ]
