# Generated by Django 6.0.1 on 2026-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_vlan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='red',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='nombre',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vlan',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
