# Generated by Django 5.2.4 on 2025-08-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iconos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=70)),
                ('ruta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('icono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.iconos')),
            ],
        ),
    ]
