# Generated by Django 5.2.4 on 2025-08-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria'),
            preserve_default=False,
        ),
    ]
