# Generated by Django 5.2.4 on 2025-08-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_servidor_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='icono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.iconos'),
        ),
    ]
