# Generated by Django 6.0.1 on 2026-02-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_servidor_puerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
