# Generated by Django 6.0.1 on 2026-03-26 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_alter_reportes_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesTelefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.CharField(max_length=100)),
                ('referenica', models.CharField(max_length=50)),
                ('num_sitio', models.IntegerField(blank=True, null=True)),
                ('contacto_sitio', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_levanta', models.DateTimeField(blank=True, null=True)),
                ('descripcion_problema', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_finales', models.TextField(blank=True, null=True)),
                ('quien_levanta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_levanta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
