# Generated by Django 6.0.1 on 2026-03-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_reportestelefonia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportestelefonia',
            name='num_sitio',
        ),
    ]
