# Generated by Django 6.0.1 on 2026-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_remove_reportestelefonia_num_sitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportestelefonia',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Cerrado')], default=1),
        ),
    ]
