# Generated by Django 6.0.1 on 2026-03-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_reportestelefonia_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportestelefonia',
            old_name='referenica',
            new_name='referencia',
        ),
    ]
