# Generated by Django 6.0.1 on 2026-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_rename_referenica_reportestelefonia_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportestelefonia',
            name='numero_contacto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportestelefonia',
            name='numero_reporte',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
